### ISSUE TITLE
Feature: Make target manager branch configurable

### ISSUE THREAD

**Issue by lvlcn-t** [caas-team/sparrow#179]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Problem Description

Currently the target manager always pushes to the `main` branch. This should be configurable to ensure that even if the registration repository's default branch is protected by a group or instance wide policy, the target manager still works correctly under another branch.

### Solution Description

Add another option to the target manager config, that allows to configure a reference to push the registration files to.

I'd propose the following config:
```yaml
targetManager:
  enabled: true
  type: gitlab
  checkInterval: 1m
  registrationInterval: 1m
  updateInterval: 120m
  unhealthyThreshold: 360m
  scheme: http
  gitlab:
    baseUrl: https://gitlab.com
    token: glpat-xxxxxxxx
    projectId: 18923
    # The branch to use for the target manager
    # Defaults to 'main'
    branch: main
```

### Who can address the issue?

Everyone
