### ISSUE TITLE
Bug: TLS for telemetry is not possible, without specifying certs

### ISSUE THREAD

**Issue by niklastreml** [caas-team/sparrow#211]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

It's not possible to use TLS for the otel exporter without passing a `telemetry.certPath`. This means impossible (or atleast annoying) to use the system's certificates.

### Expected Behavior

Sparrow should have an option like `telemetry.tls.enabled`. 
  
  If true sparrow should use the systems certificates, unless telemetry.tls.certPath is specified
 
  Otherwise use the `WithInsecure()` option

### Steps To Reproduce

1. Use this config:
```bash
cat config.yaml
```
```yaml
name: sparrow.localhost
telemetry:
  # exporter: stdout
  exporter: http
  url: some-https-jaeger.com
loader:
  type: file
  interval: 30s
  file:
    path: ./config.yaml
traceroute:
  interval: 1s
  timeout: 5s
  retries: 3
  maxHops: 32
  targets:
    - addr: telekom.de
      port: 443
```
2. `sparrow run --config config.yaml`

### Relevant logs and/or screenshots, environment information, etc.

[Code](https://github.com/caas-team/sparrow/blob/main/pkg/sparrow/metrics/exporter.go#L94-L109)

### Who can address the issue?

Anyone

### Anything else?
This should be a simple fix, since we just have to add another boolean option to the config and then optionally allow passing a certpath
