### ISSUE TITLE
Feature: Implement DNS Check

### ISSUE THREAD

**Issue by lvlcn-t** [caas-team/sparrow#81]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Problem Description

A DNS check should be implemented.

### Solution Description

For the MVP of the check, the following requirement needs to be fulfilled:
- A target is resolvable by the DNS

**Comment by lvlcn-t** [comment]
I've made up my mind around how to implement this.

## Configuration

The dns check configuration could look like this within the capabilities of the standard library:
```yaml
dns:
    interval: 1m
    timeout: 30s
    retry:
      count: 5
      delay: 1s
    targets:
      - target: example.com
      - target: 192.168.1.1:53
        nameserver: 8.8.8.8
    resolvers:
      - nameserver: 8.8.8.8
      - nameserver: 8.8.4.4
```

## Results

The results for a DNS check could then look like this:

```go
// Result represents the result of a single DNS check for a specific target
type Result struct {
    Resolved string
    Error    *error
    Total    float64
}
```

And for all targets, we can map every target to its `Result`, similar to the latency check:

```go
map[string]Result
```

### Prometheus Metrics

In addition to the API results, we could expose the following Prometheus metrics:

```go
// metrics defines the metric collectors of the DNS check
type metrics struct {
	// GaugeVec for tracking the duration of each DNS resolution
	duration *prometheus.GaugeVec
	// CounterVec for counting the total number of DNS checks
	count *prometheus.CounterVec
	// HistogramVec for detailed distribution of resolution times
	histogram *prometheus.HistogramVec
}
```

## Concerns

- The standard library doesn't have the option to specify the QueryType, so we can only lookup A and AAAA requests.
- The standard library can't validate dnssec

## Considerations

If we use the de-facto standard dns package https://godoc.org/github.com/miekg/dns, we could address the concerns and could even add additional configuration options in the future for the dns check.

A configuration with using the library could then look like this:
```yaml
  dns:
    interval: 1m
    timeout: 30s
    retry:
      count: 5
      delay: 1s
    targets:
      - target: example.com
        queryTypes:
          - A
          - AAAA
          - CNAME
      - target: 192.168.1.1:53
        nameserver: 8.8.8.8
    resolvers:
      - nameserver: 8.8.8.8
      - nameserver: 8.8.4.4
    dnssecValidation: true
```

**Comment by y-eight** [comment]
So as discussed and with my opinion I would suggest to do the following:

- Focus on the MVP: Is my target resolvable by the DNS?

We should start simple:
- Just use the locally defined DNS server
- Target should be a domain name
- Resolution time (if natively available) could be exposed by metric

Checks' config could look like:

```yaml
dns:
    interval: 1m
    timeout: 30s
    retry:
      count: 5
      delay: 1s
    targets:
      - target: example.com
 ```

With the Result struct & metrics @lvlcn-t suggestions are fine.
