### ISSUE TITLE
Feature: Implement Traceroute Check

### ISSUE THREAD

**Issue by lvlcn-t** [caas-team/sparrow#82]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

#### Features
We want to gather data similar to the output of traceroute. We want to declare a list of targets and sparrow should collect the hops through which the packets travel to reach that destination. 

#### Metrics
For now, we want to collect the following metrics for every target:
- num hops
- path taken
  - Hop number
  - IP address
#### Features
Unlike traditional traceroute, the check will be using tcp. This is to avoid requiring root permissions or cap_net_raw. I'm proposing the config to look like this:
```yaml
checks:
  traceroute:
    retry:
      delay: 10s
      count: 3
    timeout: 30s
    targets:
      - https://google.com
      - https://bing.com:80
      - https://myservice.com:12345
```

#### Metrics
Num Hops should be a simple counter:

For example: `sparrow_traceroute_hops_count{target="https://google.com"} 12`

The path taken is a bit more difficult, as we can't really convey the graph like nature of the data to prometheus. My suggestion is, we export these metrics in OpenTelemtry compatible format. We could use the otel sdk to create the metrics and then ship them of to a trace aggregator like jaeger. This makes it easy to adopt sparrow, as grafana already has a native jaeger datasource, so there would be no need for hacking together our own grafana datasource.

While we can't collect traces in prometheus, we can atleast link a timeseries to a trace using [prometheus exemplars](https://grafana.com/docs/grafana/latest/fundamentals/exemplars/). This is not a requirement, but makes the UX nicer when viewing the data in grafana
